cp 1ANO_MATEMATICA/LIVRO.tex 1ANO_PORTUGUES/LIVRO.tex
cp 1ANO_MATEMATICA/LIVRO.tex 2ANO_MATEMATICA/LIVRO.tex
cp 1ANO_MATEMATICA/LIVRO.tex 2ANO_PORTUGUES/LIVRO.tex
cp 1ANO_MATEMATICA/LIVRO.tex 3ANO_MATEMATICA/LIVRO.tex
cp 1ANO_MATEMATICA/LIVRO.tex 3ANO_PORTUGUES/LIVRO.tex
cp 1ANO_MATEMATICA/LIVRO.tex 4ANO_MATEMATICA/LIVRO.tex
cp 1ANO_MATEMATICA/LIVRO.tex 4ANO_PORTUGUES/LIVRO.tex

cp 7ANO_MATEMATICA/LIVRO.tex 5ANO_MATEMATICA/LIVRO.tex
cp 7ANO_MATEMATICA/LIVRO.tex 5ANO_PORTUGUES/LIVRO.tex
cp 7ANO_MATEMATICA/LIVRO.tex 6ANO_MATEMATICA/LIVRO.tex
cp 7ANO_MATEMATICA/LIVRO.tex 6ANO_PORTUGUES/LIVRO.tex
cp 7ANO_MATEMATICA/LIVRO.tex 7ANO_PORTUGUES/LIVRO.tex
cp 7ANO_MATEMATICA/LIVRO.tex 8ANO_MATEMATICA/LIVRO.tex
cp 7ANO_MATEMATICA/LIVRO.tex 8ANO_PORTUGUES/LIVRO.tex
cp 7ANO_MATEMATICA/LIVRO.tex 9AN0_MATEMATICA/LIVRO.tex
cp 7ANO_MATEMATICA/LIVRO.tex 9AN0_PORTUGUES/LIVRO.tex