cp 1M/.gitignore 1P/
cp 1M/.gitignore 2M/
cp 1M/.gitignore 2P/
cp 1M/.gitignore 3M/
cp 1M/.gitignore 3P/
cp 1M/.gitignore 4M/
cp 1M/.gitignore 4P/
cp 1M/.gitignore 5M/
cp 1M/.gitignore 5P/
cp 1M/.gitignore 6M/
cp 1M/.gitignore 6P/
cp 1M/.gitignore 7M/
cp 1M/.gitignore 7P/
cp 1M/.gitignore 8M/
cp 1M/.gitignore 8P/
cp 1M/.gitignore 9M/
cp 1M/.gitignore 9P/	