mv 4POR-crop.pdf 4POR.pdf
mv 6POR-crop.pdf 6POR.pdf
mv 7POR-crop.pdf 7POR.pdf
mv 8POR-crop.pdf 8POR.pdf
mv 9POR-crop.pdf 9POR.pdf
mv 1MAT-crop.pdf 1MAT.pdf
mv 2MAT-crop.pdf 2MAT.pdf
mv 3MAT-crop.pdf 3MAT.pdf
mv 4MAT-crop.pdf 4MAT.pdf
mv 6MAT-crop.pdf 6MAT.pdf
mv 7MAT-crop.pdf 7MAT.pdf
mv 8MAT-crop.pdf 8MAT.pdf
mv 5MAT-crop.pdf 5MAT.pdf
mv 9MAT-crop.pdf 9MAT.pdf
mv 5POR-crop.pdf 5POR.pdf
mv 1POR-crop.pdf 1POR.pdf
mv 2POR-crop.pdf 2POR.pdf
mv 3POR-crop.pdf 3POR.pdf
