all:
	latexmk -lualatex example1.tex   # compilador

clean:
	-rm *out *xwm *aux *log *tui *toc *.4ct *.4tc *.html *.css *.dvi *.epub *.lg *.ncx *.xref *.tmp *.idv *.opf  LIVRO.pdf *.fdb_latexmk *.fls
