cp ./_SAEB_9_MAT/media/image196.png tikz
cp ./_SAEB_9_MAT/media/image219.png tikz
cp ./_SAEB_9_MAT/media/image220.png tikz
cp ./_SAEB_9_MAT/media/image221.png tikz
cp ./_SAEB_9_MAT/media/image222.png tikz
cp ./_SAEB_9_MAT/media/image225.jpeg tikz
cp ./ilustras-mat/modulo_1-atividade_2_resposta.png tikz
cp ./ilustras-mat/modulo_1-treino_3.png tikz
cp ./ilustras-mat/modulo_10-atividade_1.png tikz
cp ./ilustras-mat/modulo_10-atividade_2.png tikz
cp ./ilustras-mat/modulo_10-atividade_3_resposta.png tikz
cp ./ilustras-mat/modulo_10-atividade_4_resposta.png tikz
cp ./ilustras-mat/modulo_10-atividade_6.png tikz
cp ./ilustras-mat/modulo_10-atividade_7.png tikz
cp ./ilustras-mat/modulo_10-atividade_9.png tikz
cp ./ilustras-mat/ tikzmodulo_10-elementos_da_circunferencia.png
cp ./ilustras-mat/modulo_10-plano_cartesiano.png tikz
cp ./ilustras-mat/modulo_10-poligonos.png tikz
cp ./ilustras-mat/modulo_10-poligonos_diagonais.png tikz
cp ./ilustras-mat/modulo_10-relacoes_de_euler.png tikz
cp ./ilustras-mat/modulo_10_-atividade_10.png tikz
cp ./ilustras-mat/modulo_11-atividade_1.png tikz
cp ./ilustras-mat/modulo_11-atividade_10_resposta.png tikz
cp ./ilustras-mat/modulo_11-atividade_4.png tikz
cp ./ilustras-mat/modulo_11-atividade_9.png tikz
cp ./ilustras-mat/modulo_11-treino_1.png tikz
cp ./ilustras-mat/modulo_11-treino_2.png tikz
cp ./ilustras-mat/modulo_11-treino_3_resposta.png tikz
cp ./ilustras-mat/modulo_11_exemplo.png tikz
cp ./ilustras-mat/modulo_12-atividade_1.png tikz
cp ./ilustras-mat/modulo_12-atividade_10.png tikz
cp ./ilustras-mat/modulo_12-atividade_2.png tikz
cp ./ilustras-mat/modulo_12-atividade_2_peca.png tikz
cp ./ilustras-mat/modulo_12-atividade_3.png tikz
cp ./ilustras-mat/modulo_12-atividade_4.png tikz
cp ./ilustras-mat/modulo_12-atividade_5_resposta.png tikz
cp ./ilustras-mat/modulo_12-atividade_6_resposta.png tikz
cp ./ilustras-mat/modulo_12-atividade_7.png tikz
cp ./ilustras-mat/modulo_12-atividade_8_resposta.png tikz
cp ./ilustras-mat/modulo_12-atividade_9.png tikz
cp ./ilustras-mat/modulo_12-treino_1.png tikz
cp ./ilustras-mat/modulo_12-treino_3.png tikz
cp ./ilustras-mat/modulo_13-atividade_10.png tikz
cp ./ilustras-mat/modulo_13-atividade_3_resposta.png tikz
cp ./ilustras-mat/modulo_13-atividade_4.png tikz
cp ./ilustras-mat/modulo_13-atividade_5.png tikz
cp ./ilustras-mat/modulo_13-atividade_7.png tikz
cp ./ilustras-mat/modulo_13-atividade_8.png tikz
cp ./ilustras-mat/modulo_13_-atividade_9c.png tikz
cp ./ilustras-mat/modulo_13_-treino_3.png tikz
cp ./ilustras-mat/modulo_14-atividade_2.png tikz
cp ./ilustras-mat/modulo_14-atividade_9_resposta.png tikz
cp ./ilustras-mat/modulo_14-exemplo.png tikz
cp ./ilustras-mat/modulo_14-exemplo_a.png tikz
cp ./ilustras-mat/modulo_14-exemplo_b.png tikz
cp ./ilustras-mat/modulo_2_potenciacao.png tikz
cp ./ilustras-mat/modulo_3-atividade_4_resposta.png tikz
cp ./ilustras-mat/modulo_3-atividade_5.png tikz
cp ./ilustras-mat/modulo_3-atividade_6.png tikz
cp ./ilustras-mat/modulo_3-atividade_7.png tikz
cp ./ilustras-mat/modulo_3-atividade_8.png tikz
cp ./ilustras-mat/modulo_3-atividade_9.png tikz
cp ./ilustras-mat/modulo_3-treino_3.png tikz
cp ./ilustras-mat/modulo_3-treino_3_opcoes.png tikz
cp ./ilustras-mat/modulo_4-atividade_3.png tikz
cp ./ilustras-mat/modulo_4-atividade_5.png tikz
cp ./ilustras-mat/modulo_4-atividade_7.png tikz
cp ./ilustras-mat/modulo_6-atividade_1.png tikz
cp ./ilustras-mat/modulo_6-atividade_3.png tikz
cp ./ilustras-mat/modulo_6-atividade_4.png tikz
cp ./ilustras-mat/modulo_6-atividade_5.png tikz
cp ./ilustras-mat/modulo_6-atividade_6.png tikz
cp ./ilustras-mat/modulo_6-atividade_8.png tikz
cp ./ilustras-mat/modulo_7-atividade_5.png tikz
cp ./ilustras-mat/modulo_7-atividade_6.png tikz
cp ./ilustras-mat/modulo_9-atividade_10.png tikz
cp ./ilustras-mat/modulo_9-atividade_3.png tikz
cp ./ilustras-mat/modulo_9-atividade_6.png tikz
cp ./ilustras-mat/modulo_9-atividade_9.png tikz
cp ./ilustras-mat/modulo_9-treino_2.png tikz
cp ./ilustras-mat/modulo_9-treino_3.png tikz
